# -*- coding: utf-8 -*-
"""Geolocation Clustering .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDFlD13Cj66qUhYYxTwq_-wi_HhTe3Ud
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv('directory.csv')

df.head()

df.tail()

df.shape

data = df[['Latitude','Longitude','City','Country']]
data = data.dropna()

df.describe()

df.dtypes

df.info()

print(df.columns)

ta = df[['Longitude','Latitude','City','Country']]
ta.dropna()

import numpy as np
from sklearn.cluster import DBSCAN

coords = np.radians(data[['Latitude', 'Longitude']])

kms_per_radian = 6371.0088
epsilon = 1 / kms_per_radian  # 1 km

db = DBSCAN(eps=epsilon, min_samples=5, metric='haversine')
data['cluster'] = db.fit_predict(coords)

import matplotlib.pyplot as plt

plt.scatter(data['Longitude'], data['Latitude'], c=data['cluster'],cmap='rainbow' )
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.title("DBSCAN Clustering of Starbucks Locations")
plt.show()

